server:
    port: 8088

upload: 
  localUrl: "/usr/local/uploadFile/"

spring: 
    #切换生产环境
    #profiles:
      #active: usage_message
    application: 
      name: spirng-boot-rabbitmq
    rabbitmq:
      host: 121.43.158.136
      port: 5672
      username: userMQ
      password: mq85444
      virtual-host: hostDemo #虚拟主机名称
      connection-timeout: 15000   #超时时间
      publisher-confirms: true    #消息发送到交换机确认机制,是否确认回调
      publisher-returns: true     #开启回调
      dynamic: true
      cache: 
        connection: 
          mode: channel
    redis: 
      jedis: 
        pool: 
          max-active: 10
          max-wait: -1
          max-idle: 100
          min-idle: 0
      host: 121.43.158.136
      prot: 6379
      password: redis85444 
      timeout: 4000
      database: 0
    datasource: 
        tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.43.158.136:3306/boot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
        username: root
        password: aaa85444
    devtools:
    restart:
      enabled: true  #设置开启热部署
mybatis: 
    ##\u5B9E\u4F53\u7C7B\u8DEF\u5F84
    typeAliasesPackage: com.xhg.pojo
    mapperLocations: classpath:mapper/*.xml
    
logging: 
    level:
      com.xhg.mapper: debug
        
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
