server:
    port: 9000
    servlet:
      context-path: /boot


upload:
  localUrl: "/usr/local/uploadFile/"

spring: 
    #切换生产环境
    #profiles:
      #active: usage_message
    application: 
      name: spirng-boot-rabbitmq
    rabbitmq:
      host: 121.43.158.136
      port: 5672
      username: userMQ
      password: mq85444
      virtual-host: hostDemo #虚拟主机名称
      connection-timeout: 15000   #超时时间
      publisher-confirm-type: correlated    #消息发送到交换机确认机制,是否确认回调
      publisher-returns: true
      dynamic: true
      cache: 
        connection: 
          mode: channel
    redis:
      prot: 6379
      #host: 121.43.158.136
      host: 129.204.224.51
      password: redis85444
      timeout: 10000
      database: 0
      lettuce:
        shutdown-timeout: 100
        pool: 
          max-active: 10 #最大连接数
          max-wait: -1   #最大阻塞等待时间 （使用负值表示没有限制） 默认-1
          max-idle: 8    #最大空闲连接 默认8
          min-idle: 0    #最小空闲连接 默认0
      sentinel:
        master: mymaster
        nodes:
          - 129.204.224.51:26379
          - 129.204.224.51:26380
          - 129.204.224.51:26381
    datasource:
        tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.43.158.136:3306/boot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
        username: root
        password: aaa85444
    devtools:
    restart:
      enabled: true  #设置开启热部署
mybatis: 
    ##\u5B9E\u4F53\u7C7B\u8DEF\u5F84
    typeAliasesPackage: com.xhg.pojo
    mapperLocations: classpath:mapper/*.xml

logging:

    level:
      com.xhg.mapper: debug
    config: classpath:logging-log4j2.yml
        
pagehelper:
  helperDialect: mysql
  reasonable: false #关闭查询超出页数时返回数据问题
  supportMethodsArguments: true
  params: count=countSql
