server:
    port: 8088

spring: 
    redis: 
      jedis: 
        pool: 
          max-active: 10
          max-wait: -1
          max-idle: 100
          min-idle: 0
      host: 121.43.158.136
      prot: 6379
      password: redis85444  
      timeout: 1000
      database: 0
    datasource: 
        tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.43.158.136:3306/boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: aaa85444
    devtools:
    restart:
      enabled: true  #设置开启热部署
mybatis: 
    ##\u5B9E\u4F53\u7C7B\u8DEF\u5F84
    typeAliasesPackage: com.xhg.pojo
    mapperLocations: classpath:mapper/*.xml
    
logging: 
    level:
      com.xhg.mapper: debug
        
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
